name: Retrieve AWS Secret and Variable

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - develop
  workflow_dispatch:

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Firstly, insert your secrets in AWS Secret Manager
      # Then, you can retrieve the secrets based on your secret-id
      # If you have multiple secret key and value pairs like mine, you can parse
      # the entire json object and print the values you'd like to display/use

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id prod/hello_app/secret_keys --query SecretString --output json)

          # Parse specific keys from the secret object
          secret_value_key1=$(echo "$secret_object" | jq -r '. | fromjson | ."lcchua-key1"')
          secret_value_key2=$(echo "$secret_object" | jq -r '. | fromjson | ."lcchua-key2"')
          secret_value_key3=$(echo "$secret_object" | jq -r '. | fromjson | ."lcchua-key3"')

          echo "Secret value Key1 is: $secret_value_key1"
          echo "Secret value Key2 is: $secret_value_key2"
          echo "Secret value Key3 is: $secret_value_key3"

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Firstly, insert your parameter in AWS Systems Manager > Parameter Store
      # Then, you can retrieve the parameters using aws ssm get-parameter command

      - name: Get parameter object
        run: |
          name_value=$(aws ssm get-parameter --name /lcchua/name --query Parameter.Value --output text)
          echo "My name is: $name_value" 

          country_value=$(aws ssm get-parameter --name /lcchua/country --query Parameter.Value --output text)
          echo "My country is: $country_value" 
